name: Release

on:
  # 在tag时触发
  push:
    tags:
      - 'v*.*.*'

jobs:
  release-zip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ZIP Component Dir
        run: |
          cd ${{ github.workspace }}/custom_components/hass_better_display
          zip -r hass_better_display.zip ./

      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/custom_components/hass_better_display/hass_better_display.zip
          asset_name: hass_better_display.zip
          tag: ${{ github.ref }}
          overwrite: true